<h1 id="tocheading">Table of Contents and Notebook Setup</h1>
<div id="toc"></div>

In [4]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

<IPython.core.display.Javascript object>

In [6]:
import numpy as np

# Univeral Function Introduction

A universal function or <i> ufunc </i> performs element wise operations on data in ndarrays. These functions include simple mathematical functions like exponentials and square roots.

In [7]:
arr = np.arange(10)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

These are referred to as <i> unary </i> ufuncs. Other functions, such as maximum take two ndarrays and return a single array (<i> binary </i> ufuncs).

In [10]:
x=np.random.randn(10)
y=np.random.randn(10)
np.maximum(x, y)

array([-0.57444477,  0.15482347,  0.76204773, -0.5933931 ,  0.96328808,
        1.43486063,  1.25790588,  0.37006007,  0.52333272,  0.18338916])

# Returning Multiple Arrays

A ufunc can also return multiple arrays; 'modf' is one example - it returns the fractional and integer part of an array of numbers:

In [11]:
arr = np.random.randn(10) * 5
arr

array([ 0.79601153, -7.10983272, -4.22078691,  3.19934598, -7.84725772,
        4.81377486, -1.93219282,  2.43285589, -1.17838245, -0.76385188])

In [13]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.79601153, -0.10983272, -0.22078691,  0.19934598, -0.84725772,
        0.81377486, -0.93219282,  0.43285589, -0.17838245, -0.76385188])

In [14]:
whole_part

array([ 0., -7., -4.,  3., -7.,  4., -1.,  2., -1., -0.])

# Returning the New Array to a New Variable

ufuncs take an optional out argument that allows them to copy the new array to a new variable:

In [18]:
arr = np.random.randn(10)
np.sqrt(arr, arr)

arr

/Users/lukepolson/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([ 1.50736221,  1.00503146,  1.21385696,         nan,  0.96791705,
               nan,         nan,  0.36897433,  0.43522152,  1.39499306])